/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Webonise' at '22/2/17 6:02 PM' with Gradle 2.3
 *
 * @author Webonise, @date 22/2/17 6:02 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
